[package]
name = "flow-node-shell"
version = "0.1.0"
edition = "2024"

[dependencies]
rsflow-core = { path = "../../rsflow-runtime/rsflow-core" }
async-trait = "0.1"
tokio = { version = "1", features = ["process", "time"] }
