[package]
name = "rsflow"
version = "0.1.0"
edition = "2024"

[dependencies]
rsflow-core = { path = "./rsflow-core" }
flow-nodes = { path = "../flow-nodes" }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

