[package]
name = "flow-node-net"
version = "0.1.0"
edition = "2024"

[dependencies]
rsflow-core = { path = "../../rsflow-runtime/rsflow-core" }
async-trait = "0.1"
hyper = { version = "0.14", features = ["full"] }